project:
  type: website

website:
  title: "David Bird"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/daviddbird
      - icon: instagram
        href: https://www.instagram.com/dav.id.bird/
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

